# Site settings
title: jeremybarkley.com 
email: jeremy@jeremybarkley.com
description: "This is my site..."
baseurl: ""
url: "http://jeremybarkley.com"
twitter_username: zombiestiltskin
github_username:  sensoph1

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-paginate]

paginate: 10
